---
- name: Install zsh
  homebrew: name=zsh

- name: Add zsh to /etc/shells
  shell: "grep '^/usr/local/bin/zsh$' /etc/shells || echo '/usr/local/bin/zsh' >> /etc/shells"
  become: True
  become_user: root

- name: Use zsh
  shell: chsh -s /usr/local/bin/zsh

- stat: path=~/.oh-my-zsh
  register: oh_my_zsh

- name: Install oh-my-zsh
  shell: curl -L http://install.ohmyz.sh | sh
  when: (use_zsh == True) and (oh_my_zsh.stat.isdir is undefined)

- name: Init rbenv for zsh
  shell: grep 'eval "$(rbenv init -)"' ~/.zshrc || echo 'eval "$(rbenv init -)"' >> ~/.zshrc
